# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dz
  pod 'RealmSwift'

end

target 'ShareExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareExtension

end
